### ISSUE TITLE
Configuration - default timezone for contacts

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#130]
Add a configuration item 'default_contact_timezone' under 'executive', eg:

``` yaml

---
production:
  executive:
    default_contact_timezone: Australia/Broken_Hill
```

If a contact does not have a timezone configured, then we will take the contact to be in this default timezone, or ENV['TZ'] if this config item is not set. 

A contact's timezone is used eg when applying time restrictions within notification rules.
