### ISSUE TITLE
Allow splitting up of config file

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#285]
To aid automatic configuration, we need to allow the config file to be decomposed into multiple files (eg one file per pikelet etc). 

Suggested structure:

A yml key (section) can map to a subdirectory or a file. 

```
/etc/flapjack
  flapjack_config.yml
  production/
    processor.yml
    notifier.yml
    gateways/
      email.yml
      jabber.yml
      ...
```

flapjack_config.yml:

```

---
production:
  pid_file: /var/run/flapjack/flapjack.pid
  log_file: /var/log/flapjack/flapjack.log
  daemonize: yes
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
```

notifier.yml:

```
notifier:
  enabled: yes
  email_queue: email_notifications
  sms_queue: sms_notifications
  jabber_queue: jabber_notifications
  pagerduty_queue: pagerduty_notifications
  notification_log_file: "/var/log/flapjack/flapjack_notification.log"
  default_contact_timezone: Australia/Sydney
  archive_events: true
  events_archive_maxage: 3600
  logger:
    level: INFO
```

The idea being it will be fully backwards compatable with the current flapjack config (single file) or allow some or all sections to be split into separate files / directories.
