### ISSUE TITLE
Document use of Jabber with Hipchat

### ISSUE THREAD

**Issue by blalor** [flapjack/flapjack#503]
Hipchat's Jabber is a bit … special.  The `alias` property of the `jabber` config block must be set to the "Room Nickname" value shown [here](https://hipchat.com/account/xmpp) (which probably only works if you're logged into hipchat).

![screen shot 2014-05-14 at 11 43 53 am](https://cloud.githubusercontent.com/assets/109915/2973562/d944985a-db7e-11e3-87a2-39d67951f8fe.png)

``` yaml
        jabber:
            enabled: yes
            queue: jabber_notifications
            server: "chat.hipchat.com"
            port: 5222
            jabberid: "<username>@chat.hipchat.com"
            password: "<password>"
            alias: "Flapjack Bot"
```
