### ISSUE TITLE
httpbroker not honoring redis connection info in flapjack config

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#635]
When I run:

```
FLAPJACK_ENV=development be bin/flapjack \
  --config etc/flapjack_config.yaml \
  receiver httpbroker
```

With the following in `etc/flapjack_config.yaml` 

``` yaml

---

development:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
```

I expect httpbroker to pick up the redis connection information, however I get this error:

```
Error: dial tcp 127.0.0.1:6380: connection refused
```

Indicating it's perhaps using a default port of 6380.
