### ISSUE TITLE
Can't get full name email syntax working

### ISSUE THREAD

**Issue by ghicks-rmn** [flapjack/flapjack#690]
Pull request 545 (https://github.com/flapjack/flapjack/pull/545) added a spec test to Flapjack demonstrating support for full name email addresses of the form "First Last <email>".

I'm attempting this with my Flapjack setup and I can't get it to work. I've tried it with and without single and double quotes, none of the combinations work - no email gets sent. But putting just an email address in the "from" field in the config, with no other changes, works fine.

Snippet of non-working config:

``` yaml
    email:
      enabled: yes
      # the redis queue this pikelet will look for notifications on
      queue: email_notifications
      logger:
        level: INFO
        syslog_errors: yes
      # these values are passed directly through to EventMachine::Protocols::SmtpClient configuration,
      # and can be omitted if the defaults are acceptable
      smtp_config:
        from: "Flapjack Example <redacted@gmail.com>"
        reply_to: redacted@gmail.com
        host: smtp.gmail.com
        port: 587
        starttls: true
        auth:
          type: 'plain'
          username: redacted@gmail.com
          password: redacted
```

Snippet of working config:

``` yaml
    email:
      enabled: yes
      # the redis queue this pikelet will look for notifications on
      queue: email_notifications
      logger:
        level: INFO
        syslog_errors: yes
      # these values are passed directly through to EventMachine::Protocols::SmtpClient configuration,
      # and can be omitted if the defaults are acceptable
      smtp_config:
        from: redacted@gmail.com
        reply_to: redacted@gmail.com
        host: smtp.gmail.com
        port: 587
        starttls: true
        auth:
          type: 'plain'
          username: redacted@gmail.com
          password: redacted
```
