### ISSUE TITLE
Add support for Slack (http://slack.com)

### ISSUE THREAD

**Issue by gwinans** [flapjack/flapjack#767]
It's becoming quite a popular tool in the admin toolchest. We use it quite a bit here.

Standing suggestion as 2.0's roadmap says we'll be able to build our own plugins.

**Comment by ali-graham** [comment]
Plugins won't be until some time after the first 2.0 release; however if anyone wants to work on a Slack gateway targeting either the `maint/1.x` or `master` branches before that time we'll do what we can to help.

It looks like the (Real Time Messaging API](https://api.slack.com/rtm), using websockets, would be needed -- so the code around network access would be fairly different between the two branches, as pre-2.0 is evented and 2.0+ uses Ruby threads.

**Comment by Hobbsee** [comment]
Slack also does XMPP, if you turn it on - https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP.  Hopefully it’ll work with minor changes, just like the HipChat gateway (which also uses XMPP) does.

**Comment by ali-graham** [comment]
Native support would be ideal, but as @Hobbsee says, the Jabber gateway works with Hipchat over XMPP, and has also been tested against Openfire and ejabberd. XMPP is a bit of a broad church, but with a few tweaks it's not too hard to get something that works everywhere.

**Comment by ali-graham** [comment]
The following settings are working for me with XMPP enabled in the Slack gateways:

```toml
  [gateways.jabber]
    enabled = true
    # Announce my arrival in the Multi-User Chat room
    chatbot_announce = true
    # the redis queue this pikelet will look for notifications on
    queue = "jabber_notifications"
    server = "[SLACK_TEAM].xmpp.slack.com"
    port = 5222
    jabberid = "[SLACK_USER]@[SLACK_TEAM].xmpp.slack.com/dev"
    password = "[PASSWORD]"
    alias = "[SLACK_USER]"
    # List of strings that this pikelet user will respond to
    identifiers = []
    # the Multi-User Chats the pikelet should join and announce to
    rooms = [
      "[SLACK_CHANNEL]@conference.[SLACK_TEAM].xmpp.slack.com"
    ]
```

Flapjack doesn't shut down cleanly, however, and the room message parsing needs to be cleaned up as currently Flapjack allows at-mentions (via @) or just the name followed by a colon (:) while Slack defaults to both.
