### ISSUE TITLE
maint/1.x - sms_gammu example config is broken

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#787]
Example config has sms_gammu as enabled but the parameters are invalid

```yaml
    sms_gammu:
      enabled: yes
      queue: sms_gammu_notifications
      from: "xxxxxxxxx"
      mysql_host: "x.x.x.x"
      mysql_database: "gammu"
      mysql_username: "gammu"
      mysql_password: "xxxxxxxx"
```

so you get https://github.com/flapjack/omnibus-flapjack/issues/73#issuecomment-74191433
