### ISSUE TITLE
Web UI - configurable groupings based on tag regexes

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#836]
Entities as a first order thing are going the way of the dodo in Flapjack 2. But we need a way of grouping checks by entity in the Web UI for those who find this abstraction useful. 

Rather than mandating the use of "entity:" prefix on entity tags, have configuration in the web gateway that defines arbitrary groupings based on tag regexes? Eg:

```toml
  [gateways.web]
    enabled = true
    [[check_grouping]]
      name = 'entity'
      plural = 'entities'
      tag_regex = '^entity:'
    [[check_grouping]]
      name = 'client'
      plural = 'clients'
      tag_regex = '^client:'
```

The tag grouping for entities should be included in the example config.

The web UI should then include links in the top level nav for each of these groupings. 

(Originally from https://github.com/flapjack/flapjack/issues/676#issuecomment-62820035)
