### ISSUE TITLE
No emails for Notifications/Alerts?

### ISSUE THREAD

**Issue by kholloway** [flapjack/flapjack#840]
I have Flapjack setup and receiving info from Sensu but Flapjack never sends out emails for alerts. The email gateway is configured and enabled (see config below) and my notification.log shows recovery/problem messages indicating an email *should* have been sent to my configured address but nothing happens beyond that. I tested with local postfix mailer then switched to mailcatcher to see if something was going on with the local mail. The local mail does work with both a telnet to port 25 test session and via mailx on the system so I know email delivery is working also. I'm sure I'm missing something simple.

I have setup the ALL entity per this link: http://flapjack.io/docs/1.0/usage/Howto-Dynamic-Entity-Contact-Linking/ and assigned my contact to it via the WebUI.

Checks in the WebUI show that my contact is assigned and would be alerted, currently the WebUI shows 1 alert for my test failure. I have my interval for alerts set at 1 second for testing but it's also been set at 15 minutes and other values, none have changed the lack of notifications.

Flapjack Version: 1.5.0

Any help would be greatly appreciated!

My contact shows the notification rule below:

```log
d4d21e06-165d-4dfc-90a3-810aed6fd882	-	-	-	-	email, sms, sms_twilio, sms_nexmo, jabber, pagerduty, sns	email, sms, sms_twilio, sms_nexmo, jabber, pagerduty, sns	[]	
```

/etc/flapjack/flapjack_config.yaml (I have tried both local mailer on port 25 and Mailcatcher as a test on port 1025, Flapjack never connects to either port and does not appear to even try to send email)
```yaml
  gateways:
    email:
      enabled: true
      logger:
        level: ERROR
      smtp_config:
        host: 127.0.0.1
        port: 1025
        domain: 'localhost.localdomain'
        from: "Flapjack Server <flapjack@noreply.com>"
        reply_to: "flapjack@noreply.com"
        starttls: false
      templates:
        alert_text: "/etc/flapjack/templates/email.text.erb"
        alert_html: "/etc/flapjack/templates/email.html.erb"
```

(Email addresses have been sanitized and are not what I'm really using)

/var/log/flapjack/notification.log
```log
2015-04-21 10:14:12 -0500 | foo-app-01:HTTP | problem | aac86117-9e95-4a2a-8932-a536405681af | email | myemail@realdomain.com
2015-04-21 10:17:06 -0500 | foo-app-01:HTTP | recovery | aac86117-9e95-4a2a-8932-a536405681af | email | myemail@realdomain.com
```
