### ISSUE TITLE
error: (/etc/flapjack/flapjack_config.yaml): did not find expected key while parsing a block mapping at line 61 column 7

### ISSUE THREAD

**Issue by IAristov** [flapjack/flapjack#882]
There is a configuration file, when commenting string from: and reply_to: then have a problem as getting in https://github.com/flapjack/flapjack/issues/817
If uncommenting - error: (/etc/flapjack/flapjack_config.yaml): did not find expected key while parsing a block mapping at line 61 column 7
```Config:
      smtp_config:
      enabled: yes
      queue: email_notifications
      logger:
        level: INFO
        syslog_errors: yes
         from: "Alert <flapjack@noreply.*.*.*>"
         reply_to: "<monitoring@*.*.*>"
        host: mail.*.*.*
        port: 26
        starttls: false
        auth:
          type: plain
          username: monitoring@*.*.*
          password: ***************
```
What is wrong?
And before that I have a problem with twillo sms. It's not send sms if sms_nexmo_queue commented.

**Comment by jessereynolds** [comment]
Could you please re-paste that config block within a code block, eg by using three backticks (`) before and after? See https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

one thing though, I think you'll need to use an email address in the from and reply_to fields, optionally with a comment eg: 

```
  from: "Alerts <alerts@example>"
```

**Comment by IAristov** [comment]
I have used all possible records, with the comment, without it, double, single and without quotes, with and without e-mail addresses. The result is always the same.
'''
        m_from = @smtp_config ? @smtp_config['from'] : "flapjack@#{@fqdn}"
        m_reply_to = @smtp_config ? ( @smtp_config['reply_to'] ||= m_from ) : "flapjack@#{@fqdn}"
        smtp_from = m_from.clone
...
        while smtp_from =~ /(<|>)/
          smtp_from.sub!(/^.*</, '')
          smtp_from.sub!(/>.*$/, '')
        end
'''
I perfectly see from this that there can be written anything before and after <>. It's not related with the shape of the recording inside the quotes. I need any new ideas.

**Comment by jessereynolds** [comment]
Which line line 67?

What version of Flapjack are you using?

Which gateways do you have enabled? 

Please send through flapjack.log for one of the runs that is failing where you have smtp from and reply_to  uncommented.

**Comment by IAristov** [comment]
Which line is line 67 (61)?
It's line   smtp_config:      (61 - e-mail: enabled: yes)

What version of Flapjack are you using?
flapjack version 1.5.0 (Ubuntu Trusty)

Which gateways do you have enabled? 
Gateways enabled for web and e-mail. Will be enabled twillio after configuring.

Please send through flapjack.log for one of the runs that is failing where you have smtp from and reply_to uncommented.
The logs (logger: level: DEBUG syslog_errors: yes) does not display anything. When I stop, start and restart the server this is only displays the line
error: (/etc/flapjack/flapjack_config.yaml): did not find expected key while parsing a block mapping at line 61 column 7

Please confirm that you don't actually have asterisks in the from and reply_to values.
I not have asterisks in the from and reply_to values.

**Comment by IAristov** [comment]
I tried on a different server. Why if exists any records in these two lines it's get the same mistake? 
         From: "Flapjack Example <flapjack@noreply.example>"
         Reply_to: "flapjack@support.example"
service flapjack restart
error: (/etc/flapjack/flapjack_config.yaml): did not find expected key while parsing a block mapping at line 63 column 7

**Comment by IAristov** [comment]
Without these two lines, it refuses to send letters. Moreover, he is trying to send them to the address, which is not present for a long time in the configuration (Line with this address (ivan.aristov@*.со.uk) grep is not finding on the server):
2015-07-13T02:58:28.868410-04:00 [DEBUG] :: flapjack-email :: new email gateway pikelet with the following options: {"enabled"=>"127.0.0.1", "port"=>25, "starttls"=>false}}
2015-07-13T02:58:28.890360-04:00 [DEBUG] :: flapjack-email :: email gateway is going into blpop mode on email_notifications
2015-07-13T02:51:59.697232-04:00 [DEBUG] :: flapjack-email :: flapjack_mailer: set from to
2015-07-13T02:51:59.701456-04:00 [DEBUG] :: flapjack-email :: preparing email to: ivan.aristov@*.co.uk, subject: Problem: 'graphana_check' on grafana is Critical, message-id: <43781880-1436770319.695231@alert-manager.wemonitor.systems>
2015-07-13T02:51:59.704602-04:00 [ERROR] :: flapjack-email :: Error generating or delivering email to ivan.aristov@*.co.uk: TypeError: can't clone NilClass
2015-07-13T02:51:59.706025-04:00 [ERROR] :: flapjack-email :: /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:86:in `clone'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:86:in `deliver'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:55:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/pikelet.rb:126:in `block in start'
2015-07-13T02:51:59.706209-04:00 [ERROR] :: flapjack-email :: Error generating or dispatching email message: TypeError: can't clone NilClass
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:86:in `clone'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:86:in `deliver'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:55:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/pikelet.rb:126:in `block in start'
2015-07-13T02:51:59.706439-04:00 [DEBUG] :: flapjack-email :: email gateway is going into blpop mode on email_notifications

**Comment by jessereynolds** [comment]
I'm finding this rather difficult to follow. 

Could you please give the exact steps needed to reproduce this issue?

**Comment by IAristov** [comment]
Sorry, this address has been added to contacts flapjack by web interface. One time I use this adress in configuration for test.
But problem with sending already exists. Error with from and reply_to lines occurs immediately upon installation (in Ubuntu Trusty or Centos 6 on VM). Maybe I deal anything wrong? My config:
```
    email:
      enabled: yes
      queue: email_notifications
      logger:
        level: DEBUG
        syslog_errors: yes
      smtp_config:
         from: "<flapjack@example.systems>" # there can be anything - example.co.uk, localhost
         reply_to: "<flapjack@example.systems>" # there can be anything - example.co.uk, localhost
        host: "mail.example.co.uk"
        port: 26
        starttls: false
        auth:
           type: plain
           username: monitoring@example.co.uk
           password: secret
```
or for postfix relay (for second error): 
```
    email:
      enabled: yes
      queue: email_notifications
      logger:
        level: DEBUG
        syslog_errors: yes
      smtp_config:
        host: "127.0.0.1"
        port: 25
        starttls: false
```

**Comment by IAristov** [comment]
Was enough to move the line from below line port. And remove the space before the quote in from. You have a very interesting configs examples.

**Comment by jessereynolds** [comment]
@IAristov could you perhaps submit a PR with any changes you'd recommend making to the example config file?

**Comment by IAristov** [comment]
To solve the above two errors I did:
flapjack_config.yaml :
```
    email:
      enabled: yes
      queue: email_notifications
      logger:
        level: DEBUG
        syslog_errors: yes
      smtp_config:
#         from: "<flapjack@example.systems>"
#         reply_to: "<flapjack@example.systems>"
        host: mail.example.com
        port: 26
        starttls: true
          from:<flapjack@example.systems>
          reply_to:<flapjack@example.systems>
        auth:
          type: plain
          username: **************@****.uk
          password: **********

```
After that config new configuration begin work, but there is still a bug described here:
https://github.com/flapjack/flapjack/issues/817
I change file 
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:
```
m_from = 'flapjack@example.systems'
#@smtp_config ? @smtp_config['from'] : "flapjack@#{@fqdn}"
```
